EFCapstone - To Do/Models/ToDoList/AddTaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class AddTaskViewModel : TaskItem
    {
        public bool IsChecked { get; set; }
        public string UserAccount { get; set; }
    }
}

EFCapstone - To Do/Models/ToDoList/ErrorPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class ErrorPageViewModel
    {
    }
}

EFCapstone - To Do/Models/ToDoList/LogInViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class LogInViewModel : User
    {
 
    }
}

EFCapstone - To Do/Models/ToDoList/RegisterUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class RegisterUserViewModel : User
    {

        [Required]
        public string PasswordConfirmation { get; set; }
    }
}

EFCapstone - To Do/Models/ToDoList/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class Task
    {
        [Required]
        public string Description { get; set; }

        [Required]
        public string IsDone { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }

    }
}

EFCapstone - To Do/Models/ToDoList/TaskItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class TaskItem
    {
        [Required]
        public string Description { get; set; }

        [Required]
        public string IsDone { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }

        public int TaskID { get; set; }
        public int UserID { get; set; }

    }
}

EFCapstone - To Do/Models/ToDoList/TaskListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class TaskListViewModel : TaskItem
    {
        public List<TaskItem> Tasks { get; set; }
    }
}

EFCapstone - To Do/Models/ToDoList/ThankYouViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class ThankYouViewModel
    {

    }
}

EFCapstone - To Do/Models/ToDoList/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Models.ToDoList
{
    public class User
    {
        public string Email { get; set; }
        public string Password { get; set; }

        public int UserID { get; set; } //don't think i needed to add this
    }
}

EFCapstone - To Do/Controllers/ToDoListController.cs
using EFCapstone___To_Do.DAL_Models;
using EFCapstone___To_Do.Models.ToDoList;
using EFCapstone___To_Do.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCapstone___To_Do.Controllers
{
    //OUTSTANDING ITEMS
    //1) Complete log in with ASP Identity
    //2) Add more front-end


    public class ToDoListController : Controller
    {
        private ToDoListDBContext _toDoListDBContext;
        private ICurrentUser _currentUser;

        public ToDoListController(ToDoListDBContext toDoListDBContext, ICurrentUser currentUser)
        {
            _toDoListDBContext = toDoListDBContext;
            _currentUser = currentUser;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LogOut()
        {
            _currentUser.CurrentUser.Email = null;
            _currentUser.CurrentUser.Password = null;
            _currentUser.loggedIn = false;
            _currentUser.CurrentUser.UserID = 0;

            var viewModel = new LogInViewModel();
            return View("LogIn", viewModel);
        }



        public IActionResult Search(string searchString)
        {
            var viewModel = new TaskListViewModel();
            var tasks = _toDoListDBContext.Tasks.Where(task => task.UserID == _currentUser.CurrentUser.UserID).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                var taskViewModelList = tasks
                    .Select(taskDAL => new TaskItem
                    {
                        Description = taskDAL.Description,
                        DueDate = taskDAL.DueDate,
                        TaskID = taskDAL.taskID,
                        UserID = taskDAL.UserID,
                        IsDone = taskDAL.IsDone
                    })
                    .Where(task => task.Description.Contains(searchString)).ToList();

                viewModel.Tasks = taskViewModelList;
                viewModel.UserAccount = _currentUser.CurrentUser.Email;

                return View("TaskList", viewModel);
            }

            return ListItems();
        }


        public IActionResult RegisterUser()
        {
            return View();
        }

        public IActionResult SortByDueDate()
        {
            var viewModel = new TaskListViewModel();
            var tasks = _toDoListDBContext.Tasks.Where(task => task.UserID == _currentUser.CurrentUser.UserID).ToList();

            var taskViewModelList = tasks
                .Select(taskDAL => new TaskItem { 
                    Description = taskDAL.Description, 
                    DueDate = taskDAL.DueDate, 
                    TaskID = taskDAL.taskID, 
                    UserID = taskDAL.UserID, 
                    IsDone = taskDAL.IsDone })
                .OrderBy(task => task.DueDate).ToList();

            viewModel.Tasks = taskViewModelList;
            viewModel.UserAccount = _currentUser.CurrentUser.Email;

            return View("TaskList", viewModel);

        }

        public IActionResult SortByCompletionStatus()
        {
            var viewModel = new TaskListViewModel();
            var tasks = _toDoListDBContext.Tasks.Where(task => task.UserID == _currentUser.CurrentUser.UserID).ToList();

            var taskViewModelList = tasks
                .Select(taskDAL => new TaskItem
                {
                    Description = taskDAL.Description,
                    DueDate = taskDAL.DueDate,
                    TaskID = taskDAL.taskID,
                    UserID = taskDAL.UserID,
                    IsDone = taskDAL.IsDone
                })
                .OrderBy(task => task.IsDone).ToList();

            viewModel.Tasks = taskViewModelList;
            viewModel.UserAccount = _currentUser.CurrentUser.Email;

            return View("TaskList", viewModel);

        }

        public IActionResult ThankYou(RegisterUserViewModel model)
        {
            if (Validation.ValidatePW(model))
            {
                var newUser = new UsersDAL();
                newUser.Email = model.Email;
                newUser.Password = model.Password;

                _toDoListDBContext.Users.Add(newUser);
                _toDoListDBContext.SaveChanges();
                return View();

            }
            return View("RegisterUser", model);

        }


        public IActionResult LogIn() //ASSUME WE CAN ONLY REACH THE LOG IN PAGE AFTER REGISTERING
        {

            return View();
         
        }

        public IActionResult SuccessfulLogIn(LogInViewModel model) 
        {
            foreach (var user in _toDoListDBContext.Users.ToList())
            {
                if (user.Email == model.Email)
                {
                    _currentUser.CurrentUser.Email = model.Email;
                    _currentUser.CurrentUser.Password = model.Password;
                    _currentUser.CurrentUser.UserID = user.userID;
                    _currentUser.loggedIn = true;
                    return View(); 
                }

            }

            return View("LogIn", model);
        }


        public IActionResult AddTask()
        {

            if (_currentUser.loggedIn == false)
            {
                var errorModel = new ErrorPageViewModel();
                return View("ErrorPage", errorModel);
            }


            var model = new AddTaskViewModel();
            model.DueDate = DateTime.Now;
            model.UserAccount = _currentUser.CurrentUser.Email;
            return View(model);
        }

        public IActionResult PushTaskToSQL(AddTaskViewModel model)
        {
            var newTask = new TasksDAL();
            newTask.Description = model.Description;
            newTask.DueDate = model.DueDate;
            newTask.IsDone = model.IsDone;

            UsersDAL userDAL = _toDoListDBContext.Users
                .Where(user => user.Email == _currentUser.CurrentUser.Email).FirstOrDefault();

            newTask.UserID = userDAL.userID; //FOREIGN KEY SET UP

            _toDoListDBContext.Tasks.Add(newTask);
            _toDoListDBContext.SaveChanges();

            return ListItems();

        }



        //ONLY GET TO THIS ACTION AFTER ADDING A TASK
        public IActionResult TaskList(AddTaskViewModel model)
        {

            //TO ACCESS TASK LIST VIEW FROM THE HEADER LINK(rather than routing from ADD TASK VIEW
            if (_currentUser.loggedIn == false)
            {
                var errorModel = new ErrorPageViewModel();
                return View("ErrorPage", errorModel);
            }

            return ListItems();
        }

        public IActionResult MarkComplete(int id)
        {

            //GET CORRECT ITEM FROM DATABASE
            var taskItem = GetTaskWhereIDIsFirstORDefault(id);
            var taskDAL = _toDoListDBContext.Tasks
                .First(taskDAL => taskDAL.taskID == taskItem.TaskID);

            taskDAL.IsDone = "YES";
            _toDoListDBContext.SaveChanges();

            //WE WANT TO CREATE A NEW LIST OF TASKS TO DISPLAY AFTER UPDATING STATUS ---PUT BELOW IN A FUNCTION!!!
            return ListItems();
        }

        public IActionResult DeleteItem(int id) 
        {
            
            var taskItem = GetTaskWhereIDIsFirstORDefault(id);
            var taskDAL = _toDoListDBContext.Tasks
                .First(taskDAL => taskDAL.taskID == taskItem.TaskID);

            _toDoListDBContext.Tasks.Remove(taskDAL);
            _toDoListDBContext.SaveChanges();

            //WE WANT TO CREATE A NEW LIST OF TASKS TO DISPLAY AFTER DELETING
            return ListItems();
        }



        //FUNCTIONS FOR REPEATED BLOCKS OF CODE
        private TaskItem GetTaskWhereIDIsFirstORDefault(int id)
        {
            TasksDAL taskDAL = _toDoListDBContext.Tasks
                .Where(task => task.taskID == id)
                .FirstOrDefault();

            var task = new TaskItem();
            task.DueDate = taskDAL.DueDate;
            task.Description = taskDAL.Description;
            task.TaskID = taskDAL.taskID;
            task.UserID = taskDAL.UserID;

            return task;
        }

        private ViewResult ListItems()
        {
            var viewModel = new TaskListViewModel();
            var tasks = _toDoListDBContext.Tasks.Where(task => task.UserID == _currentUser.CurrentUser.UserID).ToList();

            var taskViewModelList = tasks
                .Select(taskDAL => new TaskItem { Description = taskDAL.Description, DueDate = taskDAL.DueDate, TaskID = taskDAL.taskID, UserID = taskDAL.UserID, IsDone = taskDAL.IsDone}).ToList();

            viewModel.Tasks = taskViewModelList;
            viewModel.UserAccount = _currentUser.CurrentUser.Email;

            return View("TaskList", viewModel);
        }


    }
}

EFCapstone - To Do/Views/ToDoList/AddTask.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EFCapstone___To_Do.Models.ToDoList.AddTaskViewModel
    <link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />

    <h3 class="currentUser">CURRENT USER ACCOUNT: @Model.UserAccount</h3>

<br/>

<form asp-controller="ToDoList" asp-action="PushTaskToSQL" method="post">

    <br />

    <div>
        <label asp-for="Description"></label>
        <input asp-for="Description" />
    </div>

    <div>
        <label asp-for="DueDate"></label>
        <input asp-for="DueDate" />
    </div>


    <div>
            <label>TASK COMPLETE? </label><span></span>

            <label asp-for ="IsDone" class="form-check-inline">
                <input asp-for ="IsDone" type="checkbox"  value="YES" class="form-check-input">
                YES
            </label>

            <label asp-for ="IsChecked" class="form-check-inline">
                <input asp-for ="IsDone" type="checkbox" value="NO" class="form-check-input">
                NO
            </label>
        </div>

    <br />

    <button class="btn btn-dark">ADD TASK</button>

</form>

EFCapstone - To Do/Views/ToDoList/ErrorPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />

<h1 id="error">YOU MUST LOG IN TO VIEW YOUR TASKS</h1>

EFCapstone - To Do/Views/ToDoList/LogIn.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EFCapstone___To_Do.Models.ToDoList.LogInViewModel
    <link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />

<form asp-controller="ToDoList" asp-action="SuccessfulLogIn" method="post">

    <br />

    <div>
        <label asp-for="Email"></label>
        <input asp-for="Email" />
    </div>

    <div>
        <label asp-for="Password"></label>
        <input asp-for="Password" type ="password" placeholder="Please Type Your Password Here" />
    </div>

    <br />

    <button class="btn btn-dark">LOG IN</button>

</form>

EFCapstone - To Do/Views/ToDoList/RegisterUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EFCapstone___To_Do.Models.ToDoList.RegisterUserViewModel
    <link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />

    
        <form asp-controller="ToDoList" asp-action="ThankYou" method="post">

            <br />

            <div>
                <label asp-for="Email"></label>
                <input asp-for="Email" />
            </div>

            <div>
                <label asp-for="Password"></label>
                <input asp-for="Password" type="password" placeholder="Please Type Your Password Here" />
            </div>

            <div>
                <label asp-for="PasswordConfirmation">Password Confirmation:</label>
                <input asp-for="PasswordConfirmation" type="password" placeholder="Please Confirm Your Password" />
            </div>

            <br />

            <button class="btn btn-dark">CREATE ACCOUNT</button>

        </form>

EFCapstone - To Do/Views/ToDoList/SuccessfulLogIn.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />

<h1>YOU HAVE BEEN SUCCESSFULLY LOGGED IN!</h1>

EFCapstone - To Do/Views/ToDoList/TaskList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EFCapstone___To_Do.Models.ToDoList.TaskListViewModel
<link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />



<h3 class="currentUser">CURRENT USER ACCOUNT: @Model.UserAccount</h3>
<br />
<div id="search">
    <div><a class="text-important" asp-controller="ToDoList" asp-action="SortByDueDate">Sort By Due Date</a></div>
    <div><a class="text-important" asp-controller="ToDoList" asp-action="SortByCompletionStatus">Sort By Completion Status</a></div>
    <form asp-controller="ToDoList" asp-action="Search">
        <p>
            Title: <input type="text" name="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>
</div>
<br/>

<div>
    @{
        foreach (var task in Model.Tasks)
        {
            <div id="task">

                @{ if (task.IsDone == "YES")
                    {

                        <p>
                            <s>Description: @task.Description</s><br />
                            <s>Due Date: @task.DueDate</s><br />
                            <s>Complete Status: @task.IsDone</s>
                        </p>
                    }
                    else
                    {
                        <p>
                            <b>Description:</b> @task.Description<br />
                            <b>Due Date:</b> @task.DueDate<br />
                            <b>Complete Status:</b> @task.IsDone
                        </p>
                    }
                }



                @*add strike and grey out entire task*@

                <div class="tasklink"><a class="text-success" asp-controller="ToDoList" asp-action="MarkComplete" asp-route-id="@task.TaskID">Mark Item Complete</a></div>
                <div class="tasklink"><a class="text-danger" asp-controller="ToDoList" asp-action="DeleteItem" asp-route-id="@task.TaskID">Delete Task</a></div>

            </div>
            <br />

        }
    }
</div>

EFCapstone - To Do/Views/ToDoList/ThankYou.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" />

<h1>THANK YOU FOR REGISTERING! PLEASE PROCEED BY LOGGING AT THE LINK ABOVE</h1>